/**
 * Exercise Library — 211+ exercises for Apex Hypertrophy
 *
 * Each exercise has: name, muscleGroups, equipment, movementPattern,
 * isCompound, sfrRating (1–10), and optional cues.
 */

export interface ExerciseSeed {
  name: string;
  muscleGroups: string[];
  equipment: string;
  movementPattern: string;
  isCompound: boolean;
  sfrRating: number;
  cues?: string;
}

export const EXERCISE_LIBRARY: ExerciseSeed[] = [
  // ═══════════════════════════════════════════════
  // CHEST (26 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Barbell Bench Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'barbell',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 8,
    cues: 'Retract scapulae, arch back, drive feet into floor',
  },
  {
    name: 'Incline Barbell Press',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: 'barbell',
    movementPattern: 'incline_push',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Dumbbell Bench Press',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Incline Dumbbell Press',
    muscleGroups: ['chest', 'shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'incline_push',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Decline Dumbbell Press',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'decline_push',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Dumbbell Flyes',
    muscleGroups: ['chest'],
    equipment: 'dumbbell',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Incline Dumbbell Flyes',
    muscleGroups: ['chest'],
    equipment: 'dumbbell',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Cable Crossover',
    muscleGroups: ['chest'],
    equipment: 'cable',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Low Cable Fly',
    muscleGroups: ['chest'],
    equipment: 'cable',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'High Cable Fly',
    muscleGroups: ['chest'],
    equipment: 'cable',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Machine Chest Press',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'machine',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Pec Deck',
    muscleGroups: ['chest'],
    equipment: 'machine',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Push-Ups',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'bodyweight',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Weighted Dips (Chest)',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'bodyweight',
    movementPattern: 'dip',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Landmine Press',
    muscleGroups: ['chest', 'shoulders'],
    equipment: 'barbell',
    movementPattern: 'incline_push',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Smith Machine Bench Press',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'machine',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Floor Press',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Close-Grip Bench Press',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'barbell',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Svend Press',
    muscleGroups: ['chest'],
    equipment: 'dumbbell',
    movementPattern: 'squeeze',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Machine Incline Press',
    muscleGroups: ['chest', 'shoulders'],
    equipment: 'machine',
    movementPattern: 'incline_push',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Decline Barbell Press',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'barbell',
    movementPattern: 'decline_push',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Chest Dips',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'bodyweight',
    movementPattern: 'dip',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Plate Squeeze Press',
    muscleGroups: ['chest'],
    equipment: 'dumbbell',
    movementPattern: 'squeeze',
    isCompound: false,
    sfrRating: 5,
  },
  {
    name: 'Single Arm Cable Fly',
    muscleGroups: ['chest'],
    equipment: 'cable',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Incline Cable Fly',
    muscleGroups: ['chest'],
    equipment: 'cable',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Deficit Push-Ups',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'bodyweight',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 6,
  },

  // ═══════════════════════════════════════════════
  // BACK (28 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Barbell Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Pendlay Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Dumbbell Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Seated Cable Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Lat Pulldown',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable',
    movementPattern: 'vertical_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Pull-Ups',
    muscleGroups: ['back', 'biceps'],
    equipment: 'bodyweight',
    movementPattern: 'vertical_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Chin-Ups',
    muscleGroups: ['back', 'biceps'],
    equipment: 'bodyweight',
    movementPattern: 'vertical_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'T-Bar Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Chest-Supported Row',
    muscleGroups: ['back'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Cable Pullover',
    muscleGroups: ['back'],
    equipment: 'cable',
    movementPattern: 'pullover',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Straight Arm Pulldown',
    muscleGroups: ['back'],
    equipment: 'cable',
    movementPattern: 'pullover',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Meadows Row',
    muscleGroups: ['back'],
    equipment: 'barbell',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Inverted Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'bodyweight',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Machine Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'machine',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Close-Grip Lat Pulldown',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable',
    movementPattern: 'vertical_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Wide-Grip Lat Pulldown',
    muscleGroups: ['back'],
    equipment: 'cable',
    movementPattern: 'vertical_pull',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Seal Row',
    muscleGroups: ['back'],
    equipment: 'barbell',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Single Arm Lat Pulldown',
    muscleGroups: ['back'],
    equipment: 'cable',
    movementPattern: 'vertical_pull',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Kroc Row',
    muscleGroups: ['back', 'biceps'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_pull',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Rack Pull',
    muscleGroups: ['back', 'traps'],
    equipment: 'barbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Deadlift',
    muscleGroups: ['back', 'hamstrings', 'glutes'],
    equipment: 'barbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Snatch-Grip Deadlift',
    muscleGroups: ['back', 'hamstrings', 'traps'],
    equipment: 'barbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Dumbbell Pullover',
    muscleGroups: ['back', 'chest'],
    equipment: 'dumbbell',
    movementPattern: 'pullover',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Neutral Grip Pull-Ups',
    muscleGroups: ['back', 'biceps'],
    equipment: 'bodyweight',
    movementPattern: 'vertical_pull',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Machine Lat Pulldown',
    muscleGroups: ['back'],
    equipment: 'machine',
    movementPattern: 'vertical_pull',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Face Pull',
    muscleGroups: ['back', 'shoulders'],
    equipment: 'cable',
    movementPattern: 'horizontal_pull',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Reverse Fly Machine',
    muscleGroups: ['back', 'shoulders'],
    equipment: 'machine',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Kelso Shrug',
    muscleGroups: ['back', 'traps'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_pull',
    isCompound: false,
    sfrRating: 6,
  },

  // ═══════════════════════════════════════════════
  // SHOULDERS (24 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Overhead Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'barbell',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Dumbbell Shoulder Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Arnold Press',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'lateral_raise',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Cable Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: 'cable',
    movementPattern: 'lateral_raise',
    isCompound: false,
    sfrRating: 10,
  },
  {
    name: 'Machine Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: 'machine',
    movementPattern: 'lateral_raise',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Front Raise',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'front_raise',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Rear Delt Flyes',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'dumbbell',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Cable Rear Delt Fly',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'cable',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Machine Shoulder Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'machine',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Smith Machine Overhead Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'machine',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Lu Raise',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'lateral_raise',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Upright Row',
    muscleGroups: ['shoulders', 'traps'],
    equipment: 'barbell',
    movementPattern: 'upright_row',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Cable Upright Row',
    muscleGroups: ['shoulders', 'traps'],
    equipment: 'cable',
    movementPattern: 'upright_row',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Reverse Pec Deck',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'machine',
    movementPattern: 'fly',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Seated Dumbbell Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Behind The Neck Press',
    muscleGroups: ['shoulders'],
    equipment: 'barbell',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Y Raise',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'lateral_raise',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Prone Y Raise',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'dumbbell',
    movementPattern: 'lateral_raise',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Bus Driver',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'front_raise',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Band Pull-Apart',
    muscleGroups: ['shoulders', 'back'],
    equipment: 'band',
    movementPattern: 'horizontal_pull',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Pike Push-Ups',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'bodyweight',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Handstand Push-Ups',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'bodyweight',
    movementPattern: 'vertical_push',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Plate Front Raise',
    muscleGroups: ['shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'front_raise',
    isCompound: false,
    sfrRating: 5,
  },

  // ═══════════════════════════════════════════════
  // BICEPS (16 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Barbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'barbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Dumbbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Hammer Curl',
    muscleGroups: ['biceps', 'forearms'],
    equipment: 'dumbbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Preacher Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Incline Dumbbell Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Cable Curl',
    muscleGroups: ['biceps'],
    equipment: 'cable',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'EZ Bar Curl',
    muscleGroups: ['biceps'],
    equipment: 'barbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Concentration Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Spider Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Reverse Curl',
    muscleGroups: ['biceps', 'forearms'],
    equipment: 'barbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Cable Hammer Curl',
    muscleGroups: ['biceps', 'forearms'],
    equipment: 'cable',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Machine Curl',
    muscleGroups: ['biceps'],
    equipment: 'machine',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Bayesian Curl',
    muscleGroups: ['biceps'],
    equipment: 'cable',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Cross Body Curl',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Zottman Curl',
    muscleGroups: ['biceps', 'forearms'],
    equipment: 'dumbbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: '21s Curl',
    muscleGroups: ['biceps'],
    equipment: 'barbell',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 7,
  },

  // ═══════════════════════════════════════════════
  // TRICEPS (16 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Tricep Pushdown',
    muscleGroups: ['triceps'],
    equipment: 'cable',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Overhead Tricep Extension',
    muscleGroups: ['triceps'],
    equipment: 'cable',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Skull Crushers',
    muscleGroups: ['triceps'],
    equipment: 'barbell',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Dumbbell Tricep Extension',
    muscleGroups: ['triceps'],
    equipment: 'dumbbell',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Rope Pushdown',
    muscleGroups: ['triceps'],
    equipment: 'cable',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Dips (Tricep)',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'bodyweight',
    movementPattern: 'dip',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Diamond Push-Ups',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'bodyweight',
    movementPattern: 'horizontal_push',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Kickbacks',
    muscleGroups: ['triceps'],
    equipment: 'dumbbell',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Overhead Dumbbell Extension',
    muscleGroups: ['triceps'],
    equipment: 'dumbbell',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Machine Tricep Extension',
    muscleGroups: ['triceps'],
    equipment: 'machine',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'JM Press',
    muscleGroups: ['triceps'],
    equipment: 'barbell',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Tate Press',
    muscleGroups: ['triceps'],
    equipment: 'dumbbell',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Cable Overhead Extension',
    muscleGroups: ['triceps'],
    equipment: 'cable',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Bench Dips',
    muscleGroups: ['triceps'],
    equipment: 'bodyweight',
    movementPattern: 'dip',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Single Arm Pushdown',
    muscleGroups: ['triceps'],
    equipment: 'cable',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'French Press',
    muscleGroups: ['triceps'],
    equipment: 'barbell',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 7,
  },

  // ═══════════════════════════════════════════════
  // QUADS (20 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Barbell Back Squat',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'barbell',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Front Squat',
    muscleGroups: ['quads'],
    equipment: 'barbell',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Leg Press',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
    movementPattern: 'press',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Hack Squat',
    muscleGroups: ['quads'],
    equipment: 'machine',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Leg Extension',
    muscleGroups: ['quads'],
    equipment: 'machine',
    movementPattern: 'extension',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'lunge',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Walking Lunges',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'lunge',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Goblet Squat',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Smith Machine Squat',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Sissy Squat',
    muscleGroups: ['quads'],
    equipment: 'bodyweight',
    movementPattern: 'squat',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'V Squat',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Pendulum Squat',
    muscleGroups: ['quads'],
    equipment: 'machine',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Leg Press (Narrow Stance)',
    muscleGroups: ['quads'],
    equipment: 'machine',
    movementPattern: 'press',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Step Ups',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'lunge',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Reverse Lunge',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'lunge',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Cyclist Squat',
    muscleGroups: ['quads'],
    equipment: 'dumbbell',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Pistol Squat',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'bodyweight',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Wall Sit',
    muscleGroups: ['quads'],
    equipment: 'bodyweight',
    movementPattern: 'isometric',
    isCompound: false,
    sfrRating: 5,
  },
  {
    name: 'Belt Squat',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Spanish Squat',
    muscleGroups: ['quads'],
    equipment: 'band',
    movementPattern: 'squat',
    isCompound: false,
    sfrRating: 7,
  },

  // ═══════════════════════════════════════════════
  // HAMSTRINGS (16 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Romanian Deadlift',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'barbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Lying Leg Curl',
    muscleGroups: ['hamstrings'],
    equipment: 'machine',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Seated Leg Curl',
    muscleGroups: ['hamstrings'],
    equipment: 'machine',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Stiff-Leg Deadlift',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'barbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Dumbbell RDL',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Single Leg RDL',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Good Mornings',
    muscleGroups: ['hamstrings', 'back'],
    equipment: 'barbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Nordic Curl',
    muscleGroups: ['hamstrings'],
    equipment: 'bodyweight',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Glute-Ham Raise',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'bodyweight',
    movementPattern: 'curl',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Cable Pull-Through',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'cable',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Kettlebell Swing',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 6,
  },
  {
    name: 'Sumo Deadlift',
    muscleGroups: ['hamstrings', 'glutes', 'quads'],
    equipment: 'barbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Trap Bar Deadlift',
    muscleGroups: ['hamstrings', 'quads', 'glutes'],
    equipment: 'barbell',
    movementPattern: 'hip_hinge',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Standing Leg Curl',
    muscleGroups: ['hamstrings'],
    equipment: 'machine',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Swiss Ball Leg Curl',
    muscleGroups: ['hamstrings'],
    equipment: 'bodyweight',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Slider Leg Curl',
    muscleGroups: ['hamstrings'],
    equipment: 'bodyweight',
    movementPattern: 'curl',
    isCompound: false,
    sfrRating: 7,
  },

  // ═══════════════════════════════════════════════
  // GLUTES (14 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Hip Thrust',
    muscleGroups: ['glutes'],
    equipment: 'barbell',
    movementPattern: 'hip_extension',
    isCompound: true,
    sfrRating: 9,
  },
  {
    name: 'Barbell Glute Bridge',
    muscleGroups: ['glutes'],
    equipment: 'barbell',
    movementPattern: 'hip_extension',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Cable Kickback',
    muscleGroups: ['glutes'],
    equipment: 'cable',
    movementPattern: 'hip_extension',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Dumbbell Hip Thrust',
    muscleGroups: ['glutes'],
    equipment: 'dumbbell',
    movementPattern: 'hip_extension',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Smith Machine Hip Thrust',
    muscleGroups: ['glutes'],
    equipment: 'machine',
    movementPattern: 'hip_extension',
    isCompound: true,
    sfrRating: 8,
  },
  {
    name: 'Cable Pull-Through (Glute)',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: 'cable',
    movementPattern: 'hip_extension',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Frog Pump',
    muscleGroups: ['glutes'],
    equipment: 'bodyweight',
    movementPattern: 'hip_extension',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Single Leg Hip Thrust',
    muscleGroups: ['glutes'],
    equipment: 'bodyweight',
    movementPattern: 'hip_extension',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Banded Clamshell',
    muscleGroups: ['glutes'],
    equipment: 'band',
    movementPattern: 'abduction',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Cable Hip Abduction',
    muscleGroups: ['glutes'],
    equipment: 'cable',
    movementPattern: 'abduction',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Machine Hip Abduction',
    muscleGroups: ['glutes'],
    equipment: 'machine',
    movementPattern: 'abduction',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Sumo Squat',
    muscleGroups: ['glutes', 'quads'],
    equipment: 'dumbbell',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Donkey Kick',
    muscleGroups: ['glutes'],
    equipment: 'bodyweight',
    movementPattern: 'hip_extension',
    isCompound: false,
    sfrRating: 5,
  },
  {
    name: 'Fire Hydrant',
    muscleGroups: ['glutes'],
    equipment: 'bodyweight',
    movementPattern: 'abduction',
    isCompound: false,
    sfrRating: 5,
  },

  // ═══════════════════════════════════════════════
  // CALVES (8 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Standing Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'machine',
    movementPattern: 'calf_raise',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Seated Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'machine',
    movementPattern: 'calf_raise',
    isCompound: false,
    sfrRating: 9,
  },
  {
    name: 'Smith Machine Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'machine',
    movementPattern: 'calf_raise',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Leg Press Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'machine',
    movementPattern: 'calf_raise',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Dumbbell Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'dumbbell',
    movementPattern: 'calf_raise',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Single Leg Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'bodyweight',
    movementPattern: 'calf_raise',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Donkey Calf Raise',
    muscleGroups: ['calves'],
    equipment: 'machine',
    movementPattern: 'calf_raise',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Tibialis Raise',
    muscleGroups: ['calves'],
    equipment: 'bodyweight',
    movementPattern: 'dorsiflexion',
    isCompound: false,
    sfrRating: 7,
  },

  // ═══════════════════════════════════════════════
  // ABS (16 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Cable Crunch',
    muscleGroups: ['abs'],
    equipment: 'cable',
    movementPattern: 'crunch',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Hanging Leg Raise',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'leg_raise',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Ab Wheel Rollout',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'rollout',
    isCompound: false,
    sfrRating: 8,
  },
  {
    name: 'Weighted Crunch',
    muscleGroups: ['abs'],
    equipment: 'dumbbell',
    movementPattern: 'crunch',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Plank',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'isometric',
    isCompound: false,
    sfrRating: 5,
  },
  {
    name: 'Side Plank',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'isometric',
    isCompound: false,
    sfrRating: 5,
  },
  {
    name: 'Bicycle Crunch',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'crunch',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Mountain Climbers',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'dynamic',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Dragon Flag',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'leg_raise',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Decline Sit-Ups',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'crunch',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Pallof Press',
    muscleGroups: ['abs'],
    equipment: 'cable',
    movementPattern: 'anti_rotation',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Woodchop',
    muscleGroups: ['abs'],
    equipment: 'cable',
    movementPattern: 'rotation',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'V-Ups',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'crunch',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Dead Bug',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'anti_extension',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Machine Crunch',
    muscleGroups: ['abs'],
    equipment: 'machine',
    movementPattern: 'crunch',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Toes to Bar',
    muscleGroups: ['abs'],
    equipment: 'bodyweight',
    movementPattern: 'leg_raise',
    isCompound: false,
    sfrRating: 7,
  },

  // ═══════════════════════════════════════════════
  // TRAPS (8 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Barbell Shrug',
    muscleGroups: ['traps'],
    equipment: 'barbell',
    movementPattern: 'shrug',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Dumbbell Shrug',
    muscleGroups: ['traps'],
    equipment: 'dumbbell',
    movementPattern: 'shrug',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Trap Bar Shrug',
    muscleGroups: ['traps'],
    equipment: 'barbell',
    movementPattern: 'shrug',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Cable Shrug',
    muscleGroups: ['traps'],
    equipment: 'cable',
    movementPattern: 'shrug',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Smith Machine Shrug',
    muscleGroups: ['traps'],
    equipment: 'machine',
    movementPattern: 'shrug',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Farmers Walk',
    muscleGroups: ['traps', 'forearms'],
    equipment: 'dumbbell',
    movementPattern: 'carry',
    isCompound: true,
    sfrRating: 7,
  },
  {
    name: 'Overhead Shrug',
    muscleGroups: ['traps'],
    equipment: 'barbell',
    movementPattern: 'shrug',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Prone Y-T-W Raise',
    muscleGroups: ['traps', 'shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'lateral_raise',
    isCompound: false,
    sfrRating: 6,
  },

  // ═══════════════════════════════════════════════
  // FOREARMS (7 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Wrist Curl',
    muscleGroups: ['forearms'],
    equipment: 'barbell',
    movementPattern: 'wrist_curl',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Reverse Wrist Curl',
    muscleGroups: ['forearms'],
    equipment: 'barbell',
    movementPattern: 'wrist_curl',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Dumbbell Wrist Curl',
    muscleGroups: ['forearms'],
    equipment: 'dumbbell',
    movementPattern: 'wrist_curl',
    isCompound: false,
    sfrRating: 7,
  },
  {
    name: 'Behind-Back Wrist Curl',
    muscleGroups: ['forearms'],
    equipment: 'barbell',
    movementPattern: 'wrist_curl',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Plate Pinch',
    muscleGroups: ['forearms'],
    equipment: 'dumbbell',
    movementPattern: 'grip',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Dead Hang',
    muscleGroups: ['forearms'],
    equipment: 'bodyweight',
    movementPattern: 'grip',
    isCompound: false,
    sfrRating: 6,
  },
  {
    name: 'Towel Pull-Up',
    muscleGroups: ['forearms', 'back'],
    equipment: 'bodyweight',
    movementPattern: 'grip',
    isCompound: true,
    sfrRating: 6,
  },

  // ═══════════════════════════════════════════════
  // COMPOUND / FULL BODY (12 exercises)
  // ═══════════════════════════════════════════════
  {
    name: 'Clean and Press',
    muscleGroups: ['shoulders', 'quads', 'back'],
    equipment: 'barbell',
    movementPattern: 'olympic',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Power Clean',
    muscleGroups: ['back', 'quads', 'hamstrings'],
    equipment: 'barbell',
    movementPattern: 'olympic',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Thruster',
    muscleGroups: ['quads', 'shoulders'],
    equipment: 'barbell',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Dumbbell Thruster',
    muscleGroups: ['quads', 'shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'squat',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Man Maker',
    muscleGroups: ['chest', 'back', 'shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'complex',
    isCompound: true,
    sfrRating: 4,
  },
  {
    name: 'Turkish Get-Up',
    muscleGroups: ['shoulders', 'abs', 'glutes'],
    equipment: 'dumbbell',
    movementPattern: 'complex',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Barbell Complex',
    muscleGroups: ['back', 'shoulders', 'quads'],
    equipment: 'barbell',
    movementPattern: 'complex',
    isCompound: true,
    sfrRating: 4,
  },
  {
    name: 'Battle Ropes',
    muscleGroups: ['shoulders', 'abs', 'back'],
    equipment: 'cable',
    movementPattern: 'dynamic',
    isCompound: true,
    sfrRating: 4,
  },
  {
    name: 'Sled Push',
    muscleGroups: ['quads', 'glutes', 'calves'],
    equipment: 'machine',
    movementPattern: 'push',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Sled Pull',
    muscleGroups: ['back', 'hamstrings', 'biceps'],
    equipment: 'machine',
    movementPattern: 'pull',
    isCompound: true,
    sfrRating: 5,
  },
  {
    name: 'Bear Crawl',
    muscleGroups: ['abs', 'shoulders', 'quads'],
    equipment: 'bodyweight',
    movementPattern: 'dynamic',
    isCompound: true,
    sfrRating: 4,
  },
  {
    name: 'Burpee',
    muscleGroups: ['chest', 'quads', 'abs'],
    equipment: 'bodyweight',
    movementPattern: 'dynamic',
    isCompound: true,
    sfrRating: 3,
  },
];
