import type { WorkoutDayData, ProgramGoal } from '@/stores/program-store';

export interface ProgramTemplate {
  name: string;
  description: string;
  goal: ProgramGoal;
  workoutDays: WorkoutDayData[];
}

export const PROGRAM_TEMPLATES: ProgramTemplate[] = [
  {
    name: 'Push Pull Legs',
    description: 'Classic 3-day split hitting each muscle group twice per week',
    goal: 'hypertrophy',
    workoutDays: [
      {
        id: 't-ppl-1',
        name: 'Push',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Bench Press',
            muscleGroups: ['chest'],
            equipment: 'barbell',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Incline Dumbbell Press',
            muscleGroups: ['chest'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Overhead Press',
            muscleGroups: ['shoulders'],
            equipment: 'barbell',
            sets: 3,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Lateral Raise',
            muscleGroups: ['shoulders'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 15,
            setType: 'working',
          },
          {
            exerciseName: 'Tricep Pushdown',
            muscleGroups: ['triceps'],
            equipment: 'cable',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Overhead Tricep Extension',
            muscleGroups: ['triceps'],
            equipment: 'cable',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
        ],
      },
      {
        id: 't-ppl-2',
        name: 'Pull',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Row',
            muscleGroups: ['back'],
            equipment: 'barbell',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Lat Pulldown',
            muscleGroups: ['back'],
            equipment: 'cable',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Seated Cable Row',
            muscleGroups: ['back'],
            equipment: 'cable',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Face Pull',
            muscleGroups: ['shoulders'],
            equipment: 'cable',
            sets: 3,
            reps: 15,
            setType: 'working',
          },
          {
            exerciseName: 'Barbell Curl',
            muscleGroups: ['biceps'],
            equipment: 'barbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Hammer Curl',
            muscleGroups: ['biceps'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
        ],
      },
      {
        id: 't-ppl-3',
        name: 'Legs',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Back Squat',
            muscleGroups: ['quads'],
            equipment: 'barbell',
            sets: 4,
            reps: 6,
            setType: 'working',
          },
          {
            exerciseName: 'Romanian Deadlift',
            muscleGroups: ['hamstrings'],
            equipment: 'barbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Leg Press',
            muscleGroups: ['quads'],
            equipment: 'machine',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Lying Leg Curl',
            muscleGroups: ['hamstrings'],
            equipment: 'machine',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Standing Calf Raise',
            muscleGroups: ['calves'],
            equipment: 'machine',
            sets: 4,
            reps: 12,
            setType: 'working',
          },
        ],
      },
    ],
  },
  {
    name: 'Upper / Lower',
    description: '4-day split alternating upper and lower body days',
    goal: 'hypertrophy',
    workoutDays: [
      {
        id: 't-ul-1',
        name: 'Upper A',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Bench Press',
            muscleGroups: ['chest'],
            equipment: 'barbell',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Barbell Row',
            muscleGroups: ['back'],
            equipment: 'barbell',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Overhead Press',
            muscleGroups: ['shoulders'],
            equipment: 'barbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Lat Pulldown',
            muscleGroups: ['back'],
            equipment: 'cable',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Dumbbell Curl',
            muscleGroups: ['biceps'],
            equipment: 'dumbbell',
            sets: 2,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Tricep Pushdown',
            muscleGroups: ['triceps'],
            equipment: 'cable',
            sets: 2,
            reps: 12,
            setType: 'working',
          },
        ],
      },
      {
        id: 't-ul-2',
        name: 'Lower A',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Back Squat',
            muscleGroups: ['quads'],
            equipment: 'barbell',
            sets: 4,
            reps: 6,
            setType: 'working',
          },
          {
            exerciseName: 'Romanian Deadlift',
            muscleGroups: ['hamstrings'],
            equipment: 'barbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Leg Press',
            muscleGroups: ['quads'],
            equipment: 'machine',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Lying Leg Curl',
            muscleGroups: ['hamstrings'],
            equipment: 'machine',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Standing Calf Raise',
            muscleGroups: ['calves'],
            equipment: 'machine',
            sets: 4,
            reps: 15,
            setType: 'working',
          },
        ],
      },
      { id: 't-ul-3', name: 'Rest', isRestDay: true, exercises: [] },
      {
        id: 't-ul-4',
        name: 'Upper B',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Incline Dumbbell Press',
            muscleGroups: ['chest'],
            equipment: 'dumbbell',
            sets: 4,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Dumbbell Row',
            muscleGroups: ['back'],
            equipment: 'dumbbell',
            sets: 4,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Dumbbell Shoulder Press',
            muscleGroups: ['shoulders'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Cable Crossover',
            muscleGroups: ['chest'],
            equipment: 'cable',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Lateral Raise',
            muscleGroups: ['shoulders'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 15,
            setType: 'working',
          },
        ],
      },
      {
        id: 't-ul-5',
        name: 'Lower B',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Front Squat',
            muscleGroups: ['quads'],
            equipment: 'barbell',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Hip Thrust',
            muscleGroups: ['glutes'],
            equipment: 'barbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Bulgarian Split Squat',
            muscleGroups: ['quads'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Seated Leg Curl',
            muscleGroups: ['hamstrings'],
            equipment: 'machine',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Seated Calf Raise',
            muscleGroups: ['calves'],
            equipment: 'machine',
            sets: 4,
            reps: 15,
            setType: 'working',
          },
        ],
      },
    ],
  },
  {
    name: 'Full Body',
    description: '3-day full body program for maximum frequency',
    goal: 'general',
    workoutDays: [
      {
        id: 't-fb-1',
        name: 'Full Body A',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Back Squat',
            muscleGroups: ['quads'],
            equipment: 'barbell',
            sets: 3,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Barbell Bench Press',
            muscleGroups: ['chest'],
            equipment: 'barbell',
            sets: 3,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Barbell Row',
            muscleGroups: ['back'],
            equipment: 'barbell',
            sets: 3,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Lateral Raise',
            muscleGroups: ['shoulders'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 15,
            setType: 'working',
          },
          {
            exerciseName: 'Dumbbell Curl',
            muscleGroups: ['biceps'],
            equipment: 'dumbbell',
            sets: 2,
            reps: 12,
            setType: 'working',
          },
        ],
      },
      { id: 't-fb-2', name: 'Rest', isRestDay: true, exercises: [] },
      {
        id: 't-fb-3',
        name: 'Full Body B',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Deadlift',
            muscleGroups: ['back', 'hamstrings'],
            equipment: 'barbell',
            sets: 3,
            reps: 5,
            setType: 'working',
          },
          {
            exerciseName: 'Overhead Press',
            muscleGroups: ['shoulders'],
            equipment: 'barbell',
            sets: 3,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Lat Pulldown',
            muscleGroups: ['back'],
            equipment: 'cable',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Leg Press',
            muscleGroups: ['quads'],
            equipment: 'machine',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Tricep Pushdown',
            muscleGroups: ['triceps'],
            equipment: 'cable',
            sets: 2,
            reps: 12,
            setType: 'working',
          },
        ],
      },
    ],
  },
  {
    name: 'Bro Split',
    description: '5-day bodypart split for maximum volume per muscle',
    goal: 'hypertrophy',
    workoutDays: [
      {
        id: 't-bs-1',
        name: 'Chest',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Bench Press',
            muscleGroups: ['chest'],
            equipment: 'barbell',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Incline Dumbbell Press',
            muscleGroups: ['chest'],
            equipment: 'dumbbell',
            sets: 4,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Cable Crossover',
            muscleGroups: ['chest'],
            equipment: 'cable',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Pec Deck',
            muscleGroups: ['chest'],
            equipment: 'machine',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
        ],
      },
      {
        id: 't-bs-2',
        name: 'Back',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Pull-Ups',
            muscleGroups: ['back'],
            equipment: 'bodyweight',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Barbell Row',
            muscleGroups: ['back'],
            equipment: 'barbell',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Seated Cable Row',
            muscleGroups: ['back'],
            equipment: 'cable',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Straight Arm Pulldown',
            muscleGroups: ['back'],
            equipment: 'cable',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
        ],
      },
      {
        id: 't-bs-3',
        name: 'Shoulders',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Overhead Press',
            muscleGroups: ['shoulders'],
            equipment: 'barbell',
            sets: 4,
            reps: 8,
            setType: 'working',
          },
          {
            exerciseName: 'Lateral Raise',
            muscleGroups: ['shoulders'],
            equipment: 'dumbbell',
            sets: 4,
            reps: 15,
            setType: 'working',
          },
          {
            exerciseName: 'Face Pull',
            muscleGroups: ['shoulders'],
            equipment: 'cable',
            sets: 3,
            reps: 15,
            setType: 'working',
          },
          {
            exerciseName: 'Rear Delt Flyes',
            muscleGroups: ['shoulders'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
        ],
      },
      {
        id: 't-bs-4',
        name: 'Legs',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Back Squat',
            muscleGroups: ['quads'],
            equipment: 'barbell',
            sets: 4,
            reps: 6,
            setType: 'working',
          },
          {
            exerciseName: 'Romanian Deadlift',
            muscleGroups: ['hamstrings'],
            equipment: 'barbell',
            sets: 3,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Leg Extension',
            muscleGroups: ['quads'],
            equipment: 'machine',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Lying Leg Curl',
            muscleGroups: ['hamstrings'],
            equipment: 'machine',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Standing Calf Raise',
            muscleGroups: ['calves'],
            equipment: 'machine',
            sets: 4,
            reps: 15,
            setType: 'working',
          },
        ],
      },
      {
        id: 't-bs-5',
        name: 'Arms',
        isRestDay: false,
        exercises: [
          {
            exerciseName: 'Barbell Curl',
            muscleGroups: ['biceps'],
            equipment: 'barbell',
            sets: 4,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Skull Crushers',
            muscleGroups: ['triceps'],
            equipment: 'barbell',
            sets: 4,
            reps: 10,
            setType: 'working',
          },
          {
            exerciseName: 'Hammer Curl',
            muscleGroups: ['biceps'],
            equipment: 'dumbbell',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
          {
            exerciseName: 'Cable Overhead Extension',
            muscleGroups: ['triceps'],
            equipment: 'cable',
            sets: 3,
            reps: 12,
            setType: 'working',
          },
        ],
      },
    ],
  },
];
