import { create } from 'zustand';
import type { WorkoutSummaryData } from './workout-store';

interface HistoryState {
  workouts: WorkoutSummaryData[];
  addWorkout: (workout: WorkoutSummaryData) => void;
  clear: () => void;
}

const DAY = 86400000;
const now = Date.now();

const DEMO_HISTORY: WorkoutSummaryData[] = [
  {
    workoutName: 'Push',
    durationSeconds: 3420,
    totalVolume: 12400,
    totalSetsCompleted: 18,
    totalSetsPlanned: 19,
    averageRpe: 8.2,
    completedAt: now - DAY * 1,
    prs: [],
    exercises: [
      {
        exerciseName: 'Barbell Bench Press',
        muscleGroups: ['chest'],
        equipment: 'barbell',
        completedSets: 4,
        totalSets: 4,
        totalVolume: 4800,
        topWeight: 185,
        topReps: 8,
        avgRpe: 8.5,
        sets: [],
      },
      {
        exerciseName: 'Incline Dumbbell Press',
        muscleGroups: ['chest'],
        equipment: 'dumbbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 2100,
        topWeight: 70,
        topReps: 10,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Cable Crossover',
        muscleGroups: ['chest'],
        equipment: 'cable',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 1260,
        topWeight: 35,
        topReps: 12,
        avgRpe: 7.5,
        sets: [],
      },
      {
        exerciseName: 'Overhead Press',
        muscleGroups: ['shoulders'],
        equipment: 'barbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 2160,
        topWeight: 95,
        topReps: 8,
        avgRpe: 8.5,
        sets: [],
      },
      {
        exerciseName: 'Lateral Raise',
        muscleGroups: ['shoulders'],
        equipment: 'dumbbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 900,
        topWeight: 20,
        topReps: 15,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Tricep Pushdown',
        muscleGroups: ['triceps'],
        equipment: 'cable',
        completedSets: 2,
        totalSets: 3,
        totalVolume: 1180,
        topWeight: 50,
        topReps: 12,
        avgRpe: 8.0,
        sets: [],
      },
    ],
  },
  {
    workoutName: 'Legs',
    durationSeconds: 4200,
    totalVolume: 18500,
    totalSetsCompleted: 13,
    totalSetsPlanned: 13,
    averageRpe: 8.8,
    completedAt: now - DAY * 3,
    prs: [
      { exerciseName: 'Barbell Back Squat', prType: 'weight', value: 275, weight: 275, reps: 6 },
    ],
    exercises: [
      {
        exerciseName: 'Barbell Back Squat',
        muscleGroups: ['quads'],
        equipment: 'barbell',
        completedSets: 4,
        totalSets: 4,
        totalVolume: 6600,
        topWeight: 275,
        topReps: 6,
        avgRpe: 9.0,
        sets: [],
      },
      {
        exerciseName: 'Leg Press',
        muscleGroups: ['quads'],
        equipment: 'machine',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 5400,
        topWeight: 600,
        topReps: 10,
        avgRpe: 8.5,
        sets: [],
      },
      {
        exerciseName: 'Romanian Deadlift',
        muscleGroups: ['hamstrings'],
        equipment: 'barbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 3600,
        topWeight: 185,
        topReps: 10,
        avgRpe: 8.5,
        sets: [],
      },
      {
        exerciseName: 'Leg Extension',
        muscleGroups: ['quads'],
        equipment: 'machine',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 2900,
        topWeight: 120,
        topReps: 12,
        avgRpe: 9.0,
        sets: [],
      },
    ],
  },
  {
    workoutName: 'Pull',
    durationSeconds: 3600,
    totalVolume: 11200,
    totalSetsCompleted: 16,
    totalSetsPlanned: 16,
    averageRpe: 7.8,
    completedAt: now - DAY * 5,
    prs: [],
    exercises: [
      {
        exerciseName: 'Barbell Row',
        muscleGroups: ['back'],
        equipment: 'barbell',
        completedSets: 4,
        totalSets: 4,
        totalVolume: 3840,
        topWeight: 155,
        topReps: 8,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Lat Pulldown',
        muscleGroups: ['back'],
        equipment: 'cable',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 2700,
        topWeight: 120,
        topReps: 10,
        avgRpe: 7.5,
        sets: [],
      },
      {
        exerciseName: 'Seated Cable Row',
        muscleGroups: ['back'],
        equipment: 'cable',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 2160,
        topWeight: 100,
        topReps: 12,
        avgRpe: 7.5,
        sets: [],
      },
      {
        exerciseName: 'Barbell Curl',
        muscleGroups: ['biceps'],
        equipment: 'barbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 1350,
        topWeight: 75,
        topReps: 10,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Hammer Curl',
        muscleGroups: ['biceps'],
        equipment: 'dumbbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 1150,
        topWeight: 35,
        topReps: 12,
        avgRpe: 7.5,
        sets: [],
      },
    ],
  },
  {
    workoutName: 'Push',
    durationSeconds: 3300,
    totalVolume: 11800,
    totalSetsCompleted: 17,
    totalSetsPlanned: 19,
    averageRpe: 7.9,
    completedAt: now - DAY * 7,
    prs: [
      { exerciseName: 'Barbell Bench Press', prType: 'weight', value: 180, weight: 180, reps: 8 },
    ],
    exercises: [
      {
        exerciseName: 'Barbell Bench Press',
        muscleGroups: ['chest'],
        equipment: 'barbell',
        completedSets: 4,
        totalSets: 4,
        totalVolume: 4480,
        topWeight: 180,
        topReps: 8,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Incline Dumbbell Press',
        muscleGroups: ['chest'],
        equipment: 'dumbbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 1950,
        topWeight: 65,
        topReps: 10,
        avgRpe: 7.5,
        sets: [],
      },
      {
        exerciseName: 'Cable Crossover',
        muscleGroups: ['chest'],
        equipment: 'cable',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 1170,
        topWeight: 32,
        topReps: 12,
        avgRpe: 7.5,
        sets: [],
      },
      {
        exerciseName: 'Overhead Press',
        muscleGroups: ['shoulders'],
        equipment: 'barbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 2040,
        topWeight: 90,
        topReps: 8,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Lateral Raise',
        muscleGroups: ['shoulders'],
        equipment: 'dumbbell',
        completedSets: 2,
        totalSets: 3,
        totalVolume: 600,
        topWeight: 20,
        topReps: 15,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Tricep Pushdown',
        muscleGroups: ['triceps'],
        equipment: 'cable',
        completedSets: 2,
        totalSets: 3,
        totalVolume: 1560,
        topWeight: 55,
        topReps: 12,
        avgRpe: 8.0,
        sets: [],
      },
    ],
  },
  {
    workoutName: 'Legs',
    durationSeconds: 3900,
    totalVolume: 16800,
    totalSetsCompleted: 12,
    totalSetsPlanned: 13,
    averageRpe: 8.5,
    completedAt: now - DAY * 10,
    prs: [],
    exercises: [
      {
        exerciseName: 'Barbell Back Squat',
        muscleGroups: ['quads'],
        equipment: 'barbell',
        completedSets: 4,
        totalSets: 4,
        totalVolume: 6000,
        topWeight: 265,
        topReps: 6,
        avgRpe: 8.5,
        sets: [],
      },
      {
        exerciseName: 'Leg Press',
        muscleGroups: ['quads'],
        equipment: 'machine',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 4800,
        topWeight: 580,
        topReps: 10,
        avgRpe: 8.5,
        sets: [],
      },
      {
        exerciseName: 'Romanian Deadlift',
        muscleGroups: ['hamstrings'],
        equipment: 'barbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 3300,
        topWeight: 175,
        topReps: 10,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Leg Extension',
        muscleGroups: ['quads'],
        equipment: 'machine',
        completedSets: 2,
        totalSets: 3,
        totalVolume: 2700,
        topWeight: 115,
        topReps: 12,
        avgRpe: 9.0,
        sets: [],
      },
    ],
  },
  {
    workoutName: 'Pull',
    durationSeconds: 3200,
    totalVolume: 10500,
    totalSetsCompleted: 15,
    totalSetsPlanned: 16,
    averageRpe: 7.6,
    completedAt: now - DAY * 12,
    prs: [],
    exercises: [
      {
        exerciseName: 'Barbell Row',
        muscleGroups: ['back'],
        equipment: 'barbell',
        completedSets: 4,
        totalSets: 4,
        totalVolume: 3520,
        topWeight: 145,
        topReps: 8,
        avgRpe: 7.5,
        sets: [],
      },
      {
        exerciseName: 'Lat Pulldown',
        muscleGroups: ['back'],
        equipment: 'cable',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 2520,
        topWeight: 115,
        topReps: 10,
        avgRpe: 7.5,
        sets: [],
      },
      {
        exerciseName: 'Seated Cable Row',
        muscleGroups: ['back'],
        equipment: 'cable',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 2040,
        topWeight: 95,
        topReps: 12,
        avgRpe: 7.5,
        sets: [],
      },
      {
        exerciseName: 'Barbell Curl',
        muscleGroups: ['biceps'],
        equipment: 'barbell',
        completedSets: 3,
        totalSets: 3,
        totalVolume: 1260,
        topWeight: 70,
        topReps: 10,
        avgRpe: 8.0,
        sets: [],
      },
      {
        exerciseName: 'Hammer Curl',
        muscleGroups: ['biceps'],
        equipment: 'dumbbell',
        completedSets: 2,
        totalSets: 3,
        totalVolume: 1160,
        topWeight: 35,
        topReps: 12,
        avgRpe: 7.5,
        sets: [],
      },
    ],
  },
];

export const useHistoryStore = create<HistoryState>((set) => ({
  workouts: DEMO_HISTORY,

  addWorkout: (workout) => set((s) => ({ workouts: [workout, ...s.workouts] })),

  clear: () => set({ workouts: [] }),
}));
